<?php

namespace app\controllers;

use app\models\DB\Idea;
use app\models\DB\Tag;
use Yii;
use yii\db\Expression;
use yii\helpers\Url;
use yii\web\Response;

class GameController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        if(Yii::$app->user->isGuest){
            return $this->redirect(Url::to(['/']));
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionCreate(){
        $idea = new Idea();

        if($idea->load(Yii::$app->request->post()) && $idea->validate()){
            $idea->dt = new Expression('NOW()');
            $idea->save(false);

            $tagsPost = Yii::$app->request->post('tag');
            foreach($tagsPost as $tagPostKey=>$tagPostValue){
                $tagPostValue = intval($tagPostValue);
                $tagPostKey = strip_tags($tagPostKey);
                if($tagPostValue>0)$tag = Tag::findOne($tagPostValue);
                else{
                    $tag = new Tag();
                    $tag->name = $tagPostKey;
                    $tag->save();
                }
                $idea->link('tags', $tag);
            }

            return $this->redirect(Url::to(['/']));
        }

        return $this->render('idea',[
            'idea' => $idea,
            'id_user' => Yii::$app->user->id,
            'tags' => $idea->tags,
            'tagList' => Tag::find()->select(['name as value', 'name as label','id as id'])->asArray()->all(),
        ]);
    }

    /**
     * @return false|string
     */
    public function actionGettags(){
        $tagList = [];
        if(Yii::$app->request->get('term')){
            $term = Yii::$app->request->get('term');
            Yii::info($term);
            $tagList = Tag::find()
                ->where(['like','name',$term])
                ->select(['name as value', 'id as id'])
                ->asArray()
                ->all();
        }
        Yii::$app->response->format = Response::FORMAT_JSON;
        return $tagList;
    }

}
