<?php

namespace app\models\DB;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "idea".
 *
 * @property int $id
 * @property int|null $id_user
 * @property string|null $text
 * @property string|null $dt
 * @property bool $adult
 * @property bool $multiplayer
 * @property bool $vacant
 *
 * @property Game[] $games
 * @property Tag[] $tags
 * @property User $user
 */
class Idea extends \yii\db\ActiveRecord
{

    public $tagList;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'idea';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id_user'], 'integer'],
            [['adult', 'multiplayer', 'vacant'], 'boolean'],
            [['text'], 'string'],
            [['dt', 'vacant'], 'safe'],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['id_user' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_user' => 'Id User',
            'text' => 'Описание идеи',
            'dt' => 'Дата',
            'adult' => '18+',
            'multiplayer' => 'Многопользовательская',
        ];
    }

    /**
     * Gets query for [[Games]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getGames()
    {
        return $this->hasMany(Game::className(), ['id_idea' => 'id']);
    }

    /**
     * Gets query for [[Tags]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getTags()
    {
        return $this->hasMany(Tag::className(), ['id' => 'id_tag'])->viaTable('tag_idea_rel', ['id_idea' => 'id']);;
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'id_user']);
    }

    public function __get($name)
    {
        if($name=='tagList')return implode(' ',array_values(ArrayHelper::map($this->tags, 'id', 'name')));
        else return parent::__get($name); // TODO: Change the autogenerated stub
    }
}
